---
###############################################################################
#
# format to xfs File System
#
###############################################################################

# umount the mount_point (s01 or d01)
- name: umount the mount_point
  mount:
    path: "{{ vars.mount_point }}"
    fstype: ext4
    state: unmounted

# mkfs.xfs -f -s size=512 -i size=512,maxpct=0 -n ftype=1 /dev/sda1
- name: format to xfs File System
  filesystem:
    fstype: xfs
    dev: "{{ vars.disk_partition }}"
    force: yes
    opts: "-s size=512 -i size=512,maxpct=0 -n ftype=1"

# Back up the original fstab
- name: Back up the original fstab
  fetch:
    dest: ./original/
    src: /etc/fstab

# Modify /etc/fstab as below
# /dev/sda1   /s01   xfs   inode64,noatime,logbufs=8,logbsize=256k 0 0
- name: modify the /etc/fstab
  shell: " cat /etc/fstab |grep ext4|grep {{ vars.mount_point }}|grep -v '#{{ vars.disk_partition }}' "
  register: result
  ignore_errors: True

- lineinfile:
    path: /etc/fstab
    regexp: '^{{ vars.disk_partition }}'
    line: '#{{  result.stdout }}'
  when: result is succeeded

- lineinfile:
    path: /etc/fstab
    insertafter: EOF
    line: '{{ vars.disk_partition }}   {{ vars.mount_point }}   xfs   inode64,noatime,logbufs=8,logbsize=256k 0 0'
  when: result is succeeded

##### if there is something wrong happened #####
- name: rollback the original fstab
  copy:
    src: ./original/{{ ansible_host }}/etc/fstab
    dest: /etc/fstab
  when: result is failed

- name: format back to ext4 file system
  filesystem:
    fstype: ext4
    dev: "{{ vars.disk_partition }}"
    force: yes
  when: result is failed

- name: mount back to mount_point
  mount:
    src: "{{ vars.disk_partition }}"
    path: "{{ vars.mount_point }}"
    fstype: ext4
    state: mounted
  when: result is failed
################################################

# Back up the modified fstab
- name: Back up the modified fstab
  fetch:
    dest: ./modified/
    src: /etc/fstab
  when: result is succeeded

# Mount back
- name: mount back to mount_point
  mount:
    src: "{{ vars.disk_partition }}"
    path: "{{ vars.mount_point }}"
    fstype: xfs
    state: mounted
  when: result is succeeded

# use xfs_info check mount_point
- name: use xfs_info check mount_point
  shell: "xfs_info {{ vars.mount_point }}"
  ignore_errors: no
