---
###############################################################################
#
# format to xfs File System
#
###############################################################################

# check disk partition
- name: check disk partition
  shell: "cat /proc/mounts | grep {{ mount_point }} | grep 'ext4' | awk '{print $1}'"
  register: disk_partition
- debug:
    msg: "{{ disk_partition.stdout }}"

# umount the mount_point (s01 or d01)
- name: umount the mount_point
  mount:
    path: "{{ mount_point }}"
    fstype: ext4
    state: unmounted

# mkfs.xfs -f -s size=512 -i size=512,maxpct=0 -n ftype=1 /dev/sda1
- name: format to xfs File System
  filesystem:
    fstype: xfs
    dev: "{{ disk_partition.stdout }}"
    force: yes
    opts: "-s size=512 -i size=512,maxpct=0 -n ftype=1"

# Back up the original fstab
- name: Back up
  fetch:
    dest: ./backup/format-xfs/original/
    src: /etc/fstab

# Modify the /etc/fstab
- name: modify the /etc/fstab
  shell: " cat /etc/fstab |grep ext4|grep {{ mount_point }}|grep -v '#{{ disk_partition.stdout }}' "
  register: fstab_result
  ignore_errors: True

- name: comment the disk partition
  lineinfile:
    path: /etc/fstab
    regexp: '^{{ disk_partition.stdout }}'
    line: '#{{  fstab_result.stdout }}'
  when: fstab_result is succeeded

- name: add new disk partition
  lineinfile:
    path: /etc/fstab
    insertafter: EOF
    line: '{{ disk_partition.stdout }}   {{ mount_point }}   xfs   inode64,noatime,logbufs=8,logbsize=256k 0 0'
  when: fstab_result is succeeded

##### if there is something wrong happened #####
- name: rollback the original fstab
  copy:
    src: ./backup/format-xfs/original/{{ ansible_host }}/etc/fstab
    dest: /etc/fstab
  when: fstab_result is failed

- name: format back to ext4 file system
  filesystem:
    fstype: ext4
    dev: "{{ disk_partition.stdout }}"
    force: yes
  when: fstab_result is failed

- name: mount back to mount_point
  mount:
    src: "{{ disk_partition.stdout }}"
    path: "{{ mount_point }}"
    fstype: ext4
    state: mounted
  when: fstab_result is failed
################################################

# Back up the modified fstab
- name: Back up the modified fstab
  fetch:
    dest: ./backup/format-xfs/modified/
    src: /etc/fstab
  when: fstab_result is succeeded

# Mount back
- name: mount back to mount_point
  mount:
    src: "{{ disk_partition.stdout }}"
    path: "{{ mount_point }}"
    fstype: xfs
    state: mounted
  when: fstab_result is succeeded

# use xfs_info check mount_point
- name: use xfs_info check mount_point
  shell: "xfs_info {{ mount_point }}"
  ignore_errors: no
