---
###############################################################################
#
# CentOS upgrade kernel
#
###############################################################################

# check ver. info with ansible module
- debug:
    msg: "Before upgrade the version is{{ ansible_distribution_version }}"

# Back up the original yum.conf
- name: Back up yum.conf
  fetch:
    dest: ./original/
    src: /etc/yum.conf

# disable exclude settings in /etc/yum.conf
- name: modify the /etc/yum.conf
  shell: "cat /etc/yum.conf | grep centos-release* | grep exclude"
  register: yum_result

- name: comment exclude line
  lineinfile:
    path: /etc/yum.conf
    regexp: '^exclude'
    line: '#{{  yum_result.stdout }}'
  when: yum_result is succeeded

# yum remove mpitests_openmpi openmpi libibverbs cuda*
- name: yum remove packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - mpitests_openmpi
    - openmpi
    - libibverbs
    - cuda*

#  yum upgrade all
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

# enable exclude in /etc/yum.conf
- name: enable exclude line
  lineinfile:
    path: /etc/yum.conf
    regexp: '#exclude'
    line: '{{  yum_result.stdout }}'
  when: yum_result is succeeded

# Back up the modified yum.conf
- name: Back up yum.conf
  fetch:
    dest: ./modified/
    src: /etc/yum.conf

# reboot
- name: reboot
  reboot:

# check ver. info with ansible module
- debug:
    msg: "After upgrade the version is{{ ansible_distribution_version }}"