---
###############################################################################
#
# This will install the Nvidia-docker2 plugin
#
###############################################################################

# If you have nvidia-docker 1.0 installed: we need to remove it and all existing GPU containers
- name: remove existing GPU containers
  shell: "docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f"

# sudo yum remove nvidia-docker
- name: yum remove nvidia-docker
  yum:
    name: nvidia-docker
    state: absent

# Add the package repositories
- name: copy /etc/yum.repos.d/nvidia-docker.repo
  shell: "curl -s -L https://nvidia.github.io/nvidia-docker/centos7/x86_64/nvidia-docker.repo | sudo tee /etc/yum.repos.d/nvidia-docker.repo"

# Install nvidia-docker2
- name: yum install nvidia-docker2
  shell: yum install -y nvidia-docker2-2.0.3-1.docker17.03.2.ce.noarch nvidia-container-runtime-2.0.0-1.docker17.03.2.x86_64

# sudo pkill -SIGHUP dockerd
- name: kill dockerd
  shell: "pkill -SIGHUP dockerd"

# Test nvidia-smi with the latest official CUDA image
- name: test GPU containers
  shell: "docker run --runtime=nvidia --rm nvidia/cuda:10.0-base nvidia-smi"

# Back up the original /etc/docker/daemon.json
- name: Back up daemon.json
  fetch:
    dest: ./backup/nvidia-docker/original/
    src: /etc/docker/daemon.json

# # (!!) above will override /etc/docker/daemon.json, need to reconfigure (e.g. storage driver, data-root)!
- name: reconfigure daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker daemon

- meta: flush_handlers

# Back up the modified /etc/docker/daemon.json
- name: Back up daemon.json
  fetch:
    dest: ./backup/nvidia-docker/modified/
    src: /etc/docker/daemon.json
