---
###############################################################################
#
# This will install the latest Docker CE
#
###############################################################################

# sudo yum remove docker docker-ce docker-common docker-selinux docker-engine
- name: uninstall old version
  yum:
    name:
      - docker
      - docker-ce
      - docker-common
      - docker-selinux
      - docker-engine
    state: absent

# Install required packages
- name: install required packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest

# set up the stable repository
- name: set stable repository
  shell: yum-config-manager -y --add-repo https://download.docker.com/linux/centos/docker-ce.repo

# sudo yum install docker-ce 17.03.2
- name: yum install docker-ce-17.03.2
  shell: yum -y install --setopt=obsoletes=0 {{ docker_ce_ver }} {{ docker_ce_selinux_ver }}

# create a docker directory if it doesn't exist
- file:
    path: /etc/docker
    state: directory
    mode: 0755

# generate the daemon.json file:
# {
#   "graph": "{{ mount_point }}/docker",
#   "storage-driver": "overlay"
# }
- name: generate the daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

# usermod -aG docker developer
- name: Add users docker group
  user:
    name: developer
    group: docker
    append: yes
  notify: run docker daemon

- meta: flush_handlers

# logout and login 
- user: name={{ansible_user}} groups=docker
- name: reset ssh connection
  meta: reset_connection

# docker run --rm hello-world
- name: test docker
  become: no
  shell: "docker run --rm hello-world"
