---
###############################################################################
#
# Installs CUDA 10.0
#
###############################################################################

# yum -y remove `yum list installed | grep '@cuda' | cut -d. -f1 | grep -v "^[ ]" | sed -e :a -e '$!N; s/\n/ /; ta'`
- name: yum list packages
  shell: yum list installed | grep '@cuda' | cut -d. -f1 | grep -v "^[ ]" | sed -e :a -e '$!N; s/\n/ /; ta'
  register: yum_packages
- debug:
    msg: "{{ yum_packages.stdout }}"
  ignore_errors: True

# yum remove yum_packages
- name: yum remove yum_packages
  yum:
    name: "{{ yum_packages.stdout }}"
    state: absent

# copy the file to install path first
- name: copy cuda rpm file
  copy:
    src: ./files/cuda-repo-rhel7-10-0-local-10.0.130-410.48-1.0-1.x86_64.rpm
    dest: /home/developer/cuda-repo-rhel7-10-0-local-10.0.130-410.48-1.0-1.x86_64.rpm
    owner: developer
    group: developer
    mode: 0644

# sudo rpm -i cuda-repo-rhel7-10-0-local-10.0.130-410.48-1.0-1.x86_64.rpm
- name: install cuda rpm
  yum:
    name: /home/developer/cuda-repo-rhel7-10-0-local-10.0.130-410.48-1.0-1.x86_64.rpm
    state: present

# sudo yum clean all
- name: yum clean all
  command: yum clean all
  ignore_errors: True

# sudo yum install cuda
- name: yum install cuda
  yum:
    name: cuda
    state: latest
    update_cache: yes

# Back up the original /etc/profile.d/cuda.sh
- name: Back up cuda.sh
  fetch:
    dest: ./backup/nvidia-cuda/original/
    src: /etc/profile.d/cuda.sh

# copy the public version of cuda.sh to target
- name: copy cuda.sh
  copy:
    src: ./files/cuda.sh
    dest: /etc/profile.d/cuda.sh
    owner: root
    group: root
    mode: 0644

# Back up the modified /etc/profile.d/cuda.sh
- name: Back up cuda.sh
  fetch:
    dest: ./backup/nvidia-cuda/modified/
    src: /etc/profile.d/cuda.sh
  notify: reboot

- meta: flush_handlers

# delete the cuda-repo-rhel7-10-0-local-10.0.130-410.48-1.0-1.x86_64.rpm
- name: delete the cuda rpm
  file:
    path: /home/developer/cuda-repo-rhel7-10-0-local-10.0.130-410.48-1.0-1.x86_64.rpm
    state: absent
